Updates for .NET 8 - release-4.0
Particular/NServiceBus.Gateway pull request #603
Opened 2024-03-11 19:46 UTC by particularbot

* Set CI workflow `dotnet-version` to `8.0.x`, `7.0.x`, `6.0.x`
* Set release workflow `dotnet-version` to `8.0.x`
* Set test project target frameworks to `(net481);net6.0;net7.0;net8.0`
* Set `pwsh` as default shell for CI and Release workflows
* Use `Particular/push-octopus-package-action@main` with comment
* Update GitHub Actions versions:
    * `actions/checkout` to `v4.1.1`
    * `actions/setup-dotnet` to `v4.0.0`
    * `actions/upload-artifact` to `v4.3.1`
    * `Particular/run-tests-action` to `v1.7.0`
    * `Particular/push-octopus-package-action` to `v2.0.0`
    * `azure/login` to `v2.0.0`
    * `Particular.Approvals` to `0.3.0` if using `0.2.0`
* Update build tool NuGet package versions in test projects:
    * `GitHubActionsTestLogger` to `2.3.3`
    * `Microsoft.NET.Test.Sdk` to `17.9.0`
    * `NUnit` to `3.14.0`
    * `NUnit3TestAdapter` to `4.5.0`

2024-03-12 16:03 UTC, DavidBoike requested changes

2024-03-13 11:00 UTC, ramonsmits commented on src/NServiceBus.Gateway.AcceptanceTests/NServiceBus.Gateway.AcceptanceTests.csproj
> -  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
Interesting

2024-03-13 13:13 UTC, DavidBoike commented on src/NServiceBus.Gateway.PersistenceTests/NServiceBus.Gateway.PersistenceTests.csproj
> +    <PackageReference Include="NUnit" Version="[3.14.0, 4.0.0)" />
This should be reverted

2024-03-14 14:40 UTC, DavidBoike approved these changes

2024-03-14 14:40 UTC, merged